foodorderproject/foodorderproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menucard.urls')),
]

foodorderproject/menucard/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views
from .views import *
from django.views.generic.base import TemplateView


urlpatterns = [
    path('', home, name='home'),
    path('main/', main, name='main'),
    path('about/', about, name='about'),
    path('index/', index, name='index'),
    path('order/', order, name='order'),
    path('order_form/', order_form, name='order_form'),
    #path('createorder/', createorder, name='createorder'),
    path('showmain/', showmain, name='showmain'),
    path('showmain2/', showmain2, name='showmain2'),
    path('createform/', createform, name='createform'),
    path('updateform/<int:id>/', updateform, name='updateform'),
    path('showmain3/', showmain3, name='showmain3'),
    path('showmain4/', showmain4, name='showmain4'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('deleteform/<int:id>/', deleteform, name='deleteform'),
    path('signup/', signup, name='signup'),
    path('login/', views.LoginView.as_view(template_name='menucard/registration/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view, name='logout'),
]
app_name = 'menucard'

foodorderproject/menucard/models.py
from django.db import models

# Create your models here.

class Menu(models.Model):
    dish_number = models.IntegerField()
    dish_name = models.CharField(max_length=100)
    #dish_price = models.IntegerField()

    def __str__(self):
        return self.dish_name


class Orderid(models.Model):
    STATUS = (
        ('Progressing', 'Progressing'),
        ('Prepared', 'Prepared'),
        ('Completed', 'Completed'),
    )

    ordernumber = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    #total = models.CharField(max_length=30)
    datetime = models.DateTimeField(auto_now_add=True)
    fooditem = models.ForeignKey(Menu, on_delete=models.SET_NULL, null=True, blank=True)
    order_status = models.CharField(max_length=100, choices=STATUS, default='Progressing')

    def __str__(self):
        return self.name

foodorderproject/menucard/forms.py
from django.forms import ModelForm
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class OrderForm(ModelForm):
    class Meta:
        model = Orderid
        fields = '__all__'

class CreateForm(ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'

class UpdateForm(ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'

class DeleteForm(ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = User
        fields = ('email', 'password1')

foodorderproject/menucard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(requests):
    return render(requests, 'menucard/main.html')

def main(requests):
    return render(requests, 'menucard/main.html')

def about(requests):
    return render(requests, 'menucard/about.html')

def index(requests):
    return render(requests, 'menucard/index.html')

def order(request):
	st=Menu.objects.all()
	return render(request,'menucard/order.html',{'st':st})

def order_form(requests):
    form = OrderForm()
    if requests.method == 'POST':
        print("request.post", requests.POST)

        form = OrderForm(requests.POST)
        if form.is_valid():
            form.save()
            return redirect('menucard:order')
    context = {'form': form}
    return render(requests, 'menucard/order_form.html', context)

def showmain(request):
    last_order=Orderid.objects.last()
    return render(request,'menucard/showmain.html', {'last_order':last_order})

def showmain2(request):
	allorders=Orderid.objects.filter(order_status='Progressing')
	return render(request,'menucard/showmain2.html',{'allorders':allorders})

def showmain3(request):
	allorders=Orderid.objects.filter(order_status='completed')
	return render(request,'menucard/showmain3.html',{'allorders':allorders})

def showmain4(request):
	allorders=Orderid.objects.filter(order_status='prepared')
	return render(request,'menucard/showmain4.html',{'allorders':allorders})

@login_required(login_url='menucard:login')
def createform(requests):
    form = CreateForm()
    if requests.method == 'POST':
        print("request.post", requests.POST)

        form = CreateForm(requests.POST)
        if form.is_valid():
            form.save()
            return redirect('menucard:order')
    context = {'form': form}
    return render(requests, 'menucard/createform.html', context)

@login_required(login_url='menucard:login')
def updateform(requests, id):
    obj = Menu.objects.get(id=id)
    form = UpdateForm(instance=obj)
    if requests.method == 'POST':
        form = UpdateForm(requests.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('menucard:order')
    context = {'form': form}
    return render(requests, 'menucard/updateform.html', context)

@login_required(login_url='menucard:login')
def deleteform(requests, id):
    obj = Menu.objects.get(id=id)
    if requests.method == 'POST':
        obj.delete()
        return redirect('menucard:order')
    context = {'item': obj}
    return render(requests, 'menucard/deleteform.html', context)

def signup(requests):
    if requests.method == 'POST':
        form = SignUpForm(requests.POST)

        if form.is_valid():
            user = form.save()
            login(requests, user)
            return redirect('menucard:home')
    else:
        form = SignUpForm()
    return render(requests, 'menucard/registration/signup.html', {'form': form})

def login(requests):
    return render(requests, 'menucard/registration/login.html')

foodorderproject/menucard/templates/menucard/about.html
{% load static %}  

{% block header %}
{% include 'menucard/layout/navbar.html' %}
{% endblock %}

<div class="aboutpicture">
    <img src="{% static 'images/about.jpg' %}" alt="about" class="img-fluid">
</div>


<div class="jumbotron">
    <h1 class="display-5">About us</h1>
    <h1 class="display-4">Generic Restaurant Pvt. Ltd.</h1>
    <p class="lead">We welcome you to sit back, unwind and appreciate the lovely sights and hints of the ocean while our best gourmet expert sets you up a scrumptious dinner utilizing the best and freshest ingredients. Generic Company's legacy comes from The Old Generic Restaurant itself which was built up in 1963.
    </p>
    <p class="lead">Generic Restaurant has worked for people in general and has advanced into a combination between exquisite chic and contemporary fine charge.</p>
    <hr class="my-4">
    <p>Enjoy our dazzling dishes and make the most of your eating background with us!</p>
    <p>Dont forget to rate and post your reviews about us. </p>
    <p class="lead">
      <h4> For further enquiries </h4>
      <a class="btn btn-primary btn-lg" href="https://mail.google.com" role="button">Email us at Hotel@besthotel.com</a>
    </p>
  </div>

foodorderproject/menucard/templates/menucard/createform.html
{% load static %}  

{% block header %}
{% include 'menucard/layout/navbar.html' %}
{% endblock %}


<div class="jumbotron">
    <h1 class="display-4">Add new items to Menu (only for admins)</h1>
    <p class="lead">
        <form method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" class="btn-danger" name="submit">
        
        </form> </p>
      <a class="btn btn-primary btn-lg" href="../order" role="button">Back to Menu</a>
    </p>
  </div>

foodorderproject/menucard/templates/menucard/deleteform.html
{% load static %}  

{% block header %}
{% include 'menucard/layout/navbar.html' %}
{% endblock %}


<div class="jumbotron">
    <h1 class="display-4">Delete items from Menu (only for admins)</h1>
    <p class="lead">
        <form method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" class="btn-danger" name="submit">
        
        </form> </p>
      <a class="btn btn-primary btn-lg" href="../order" role="button">Back to Menu</a>
    </p>
  </div>

foodorderproject/menucard/templates/menucard/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Food Order</title>  
    {% load static %}  
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">  
    <script src="{% static 'bootstrap.min.js' %}"></script>  
    <script>alert("BLank")</script>
</head>  
<body>
NOTHING HERE

</body>  
</html>  

foodorderproject/menucard/templates/menucard/layout/navbar.html
<head>  
    <meta charset="UTF-8">  
    <title>Title</title>  
    {% load static %}  
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">  
    <script src="{% static 'bootstrap.min.js' %}"></script>  
</head>  

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Food Order</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="../main">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="../order">Order <span class="sr-only">(current)</span></a>
          </li>
        <li class="nav-item active">
            <a class="nav-link" href="../about">About <span class="sr-only">(current)</span></a>
          </li>

          {% if request.user.is_authenticated %}
          <li class = "nav-item active"><a class="nav-link" href = "logout">Logout</a></li>
          {% endif %}
      </ul>
  
    </div>
  </nav>

foodorderproject/menucard/templates/menucard/main.html
{% load static %}  


{% block header %}
{% include 'menucard/layout/navbar.html' %}
{% endblock %}


<a class="btn btn-success btn-lg btn-block" href="../showmain3" role="button">Orders Completed today</a>
<br>
<a class="btn btn-secondary btn-lg btn-block" href="../showmain2" role="button">Orders in progress</a>
<br>
<a class="btn btn-primary btn-lg btn-block" href="../showmain4" role="button">Orders prepared</a>
<br>
<a class="btn btn-danger btn-lg btn-block" href="../showmain" role="button">New Orders</a>
<br>

foodorderproject/menucard/templates/menucard/order.html
{% load static %}  


{% block header %}
{% include 'menucard/layout/navbar.html' %}
{% endblock %}


<table class="table table-striped">
    <thead>
      <tr>
        <th>Dish id</th>
        <th>Food Item</th>
        <!--<th>Price</th>
         <th>Buy</th> -->
      </tr>
    </thead>
    
    <tbody>
    {% for sts in st %}
      <tr>
        <td>{{sts.id}}</td>
        <td>{{sts.dish_name}}</td>
        <td>{{sts.dish_price}}</td>
        <td> <a href =  "{% url 'menucard:updateform' sts.id %}" > <button class="btn btn-danger btn-lg" > Update </button> </a> </td> 
        <td> <a href =  "{% url 'menucard:deleteform' sts.id %}" > <button class="btn btn-danger btn-lg" > Delete </button> </a> </td>
      </tr>
      {% endfor %}
      
    </tbody>

  </table>
  <hr>

   <a href="../order_form" class="btn btn-success btn-lg">Make order</a> <br><br>

   <a href="../createform" class="btn btn-danger btn-lg">Add Menu items (only for Manager)</a>

 

 

foodorderproject/menucard/templates/menucard/order_form.html
{% load static %}  

{% block header %}
{% include 'menucard/layout/navbar.html' %}
{% endblock %}

<div class="jumbotron">
    <h1 class="display-4">Place order</h1>
    <p class="lead">
        <form method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" class="btn-success" name="submit">
        
        </form> </p>
      <a class="btn btn-primary btn-lg" href="../order" role="button">Back to Menu</a>
    </p>
  </div>

foodorderproject/menucard/templates/menucard/showmain.html
{% load static %}  


{% block header %}
{% include 'menucard/layout/navbar.html' %}
{% endblock %}




<div class="jumbotron">
    <h1 class="display-4">New orders:  </h1>
    <p class="lead">{{last_order.name}}'s order of {{last_order.fooditem}} at {{last_order.datetime}}</p>
      <a class="btn btn-primary btn-lg" href="../main" role="button">Go to homepage</a>
    </p>
  </div>

foodorderproject/menucard/templates/menucard/showmain2.html
{% load static %}  


{% block header %}
{% include 'menucard/layout/navbar.html' %}
{% endblock %}

<div class="jumbotron">
    <h1 class="display-4">Orders in progress: </h1>
    <p class="lead">{% for lor in allorders %}
        <br>
        {{lor.ordernumber}}. {{lor.name}}'s order of {{lor.fooditem}} at {{lor.datetime}}
        {% endfor %}</p>
      <a class="btn btn-primary btn-lg" href="../main" role="button">Go to homepage</a>
    </p>
  </div>

foodorderproject/menucard/templates/menucard/showmain3.html
{% load static %}  


{% block header %}
{% include 'menucard/layout/navbar.html' %}
{% endblock %}

<div class="jumbotron">
    <h1 class="display-4">Orders completed: </h1>
    <p class="lead">{% for lor in allorders %}
        <br>
        {{lor.ordernumber}}. {{lor.name}}'s order of {{lor.fooditem}} at {{lor.datetime}}
        {% endfor %}</p>
      <a class="btn btn-primary btn-lg" href="../main" role="button">Go to homepage</a>
    </p>
  </div>

foodorderproject/menucard/templates/menucard/showmain4.html
{% load static %}  


{% block header %}
{% include 'menucard/layout/navbar.html' %}
{% endblock %}

<div class="jumbotron">
    <h1 class="display-4">Orders prepared: </h1>
    <p class="lead">{% for lor in allorders %}
        <br>
        {{lor.ordernumber}}. {{lor.name}}'s order of {{lor.fooditem}} at {{lor.datetime}}
        {% endfor %}</p>
      <a class="btn btn-primary btn-lg" href="../main" role="button">Go to homepage</a>
    </p>
  </div>

foodorderproject/menucard/templates/menucard/updateform.html
{% load static %}  

{% block header %}
{% include 'menucard/layout/navbar.html' %}
{% endblock %}

<div class="jumbotron">
    <h1 class="display-4">Create Order (only for admins)</h1>
    <p class="lead">
        <form method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" class="btn-danger" name="submit">
        
        </form> </p>
      <a class="btn btn-primary btn-lg" href="../order" role="button">Back to Menu</a>
    </p>
  </div>